### ISSUE TITLE
MQTT Broker username/password - required/optional

### ISSUE THREAD

**Issue by andypiper** [mhawkshaw/homebridge-enviroplus#8]
**Describe The Bug:**

Half bug, half feature request. 

- I don't have a username or password required for connection to my personal MQTT broker (this is not great practice, but it's fully internal to my home network, for personal use, has no really sensitive data on it, and is only used for various internal projects).
- homebridge-enviroplus has the username and password fields marked as required, so when I upgraded to 2.0.x I thought to myself, ok, I'll try putting something "blank-ish" like a space, or `""`.
  - the plugin appeared to start (no errors in the log) but the sensors showed with weird values (-270 temperature), which I now know are the default values it sets up, from looking at the code
  - I deleted the username and password values, the UI showed a warning that they were required fields, but saved the config anyway.
  - I checked `config.json` and observed that the values did not exist in the file.
  - I restarted HB and things started to work / obviously the MQTT connection is working ok without them.

Ideally for my own use, those fields would be optional *however* I also accept that this may not be a recommended mosquitto / broker configuration.

Suggestions:
 - make the fields optional; OR
 - make the fields required, and enforce that they are included at saving (although that might be a Homebridge UI issue rather than in the plugin); OR
 - make the fields required, and provide an option to set them to blank / not send them as part of the MQTT conection.

Additional related suggestion:
 - provide more verbose logging around MQTT connection and config at startup

**Plugin Config:**

```json
        {
            "mqttbroker": "mqtt://127.0.0.1:1883",
            "topic": "enviroplus",
            "serial": "1234567890",
            "excellent": 10,
            "good": 20,
            "fair": 25,
            "inferior": 50,
            "poor": 50,
            "platform": "EnviroplusAirQuality"
        },
```

**Environment:**

* **Plugin Version**: 2.0.2
* **Homebridge Version**: 1.5.0
* **Node.js Version**: 16.16
* **NPM Version**: 8.11
* **Operating System**: Homebridge Raspbian v1.0.23

**Comment by mhawkshaw** [comment]
I recommend setting a username and password - your network is only as secure as the weakest link. Nonetheless I did test with having no username and password set, but not from the GUI. This is now fixed. Also added some additional log messages. You can see even more log messages by starting homebridge with the -D flag to show debug messages.

**Comment by andypiper** [comment]
Makes sense. Thanks!
